version: '3.8'

services:
  analyzer:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    environment:
      - BASE_PATH=/data
    env_file:
      - ./deploy/config/.env
    volumes:
      - ./deploy/data/sources:/data

  minio:
    image: minio/minio
    hostname: sentry.minio
    command: server /data --console-address ":9001"
    env_file:
      - ./deploy/config/.env
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 3

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./deploy/init/createbucket.sh:/etc/createbucket.sh
      - ./deploy/data/sources:/data
    env_file:
      - ./deploy/config/.env
    entrypoint: /etc/createbucket.sh
