name: scs-tool

services:
  minio:
    image: minio/minio
    hostname: scs.minio
    command: server /data --console-address ":9001"
    env_file:
      - ./config/.env
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 3

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./createbucket.sh:/etc/createbucket.sh
      - ./data/sources:/data
    env_file:
      - ./config/.env
    entrypoint: /etc/createbucket.sh
