# Generated by Django 5.0.6 on 2024-06-23 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(max_length=42)),
                ("source", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("report", models.JSONField()),
                (
                    "analyzer",
                    models.CharField(
                        choices=[
                            ("semgrep", "Semgrep"),
                            ("openai", "Openai"),
                            ("mythril", "Mythril"),
                            ("slither", "Slither"),
                        ],
                        max_length=7,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="contracts.contract"
                    ),
                ),
            ],
        ),
    ]
